config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :events do
    resources :registrations do
      member do
        get 'steps/1' => 'registrations#step1', :as => :step1
        patch 'steps/1/update' => 'registrations#step1_update', :as => :update_step1
        get 'steps/2' => 'registrations#step2', :as => :step2
        patch 'steps/2/update' => 'registrations#step2_update', :as => :update_step2
        get 'steps/3' => 'registrations#step3', :as => :step3
        patch 'steps/3/update' => 'registrations#step3_update', :as => :update_step3
      end
    end
  end

  resource :user

  namespace :admin do
    root "events#index"

    resources :versions do
      post :undo
    end

    resources :events do
      resources :tickets, :controller => "event_tickets"
      resources :registrations, :controller => "event_registrations"

      member do
        post :reorder
      end

      collection do
        post :bulk_update
      end
    end
    resources :users do
      resource :profile, :controller => "user_profiles"

      member do
        post :reorder
      end
    end
  end

  root "events#index"

  get '/faq' => "pages#faq"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :memberships
  has_many :groups, through: :memberships
  has_one :profile

  has_many :registrations

  accepts_nested_attributes_for :profile

  include RankedModel
  ranks :row_order

  def display_name
    self.email.split("@").first
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def index
    @users = User.includes(:groups).rank(:row_order).all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  def reorder
    @user = User.find(params[:id])
    @user.row_order_position = params[:position]
    @user.save!

    respond_to do |format|
      format.html { redirect_to admin_users_path }
      format.json { render :json => { :message => "ok" } }
    end
  end

  protected

  def user_params
    params.require(:user).permit(:email, :group_ids => [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user

  def show
  end

  def edit
    # 跟剛才後台情況一樣，如果沒有 @user.profile，要先新建一個
    # unless @user.profile 等同於 if !@user.profile 或 if @user.profile.nil?
    @user.create_profile unless @user.profile
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "修改成功"
      redirect_to edit_user_path
    else
      render "edit"
    end
  end

  protected

  def user_params
    params.require(:user).permit(:time_zone, :profile_attributes => [:id, :legal_name, :birthday, :location, :education, :occupation, :bio, :specialty])
  end

  def find_user
    @user = current_user
    @user.create_profile unless @user.profile
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>Edit User</h1>

<% if @user.errors.any? %>
  <div class="error_explanation">
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for [:admin, @user]  do |f| %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :group_ids %>
    <%= f.select :group_ids, Group.all.map{ |group| [group.name, group.id]}, {}, multiple: true, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Update", class:"btn btn-primary" %>
    <%= link_to "Cancel", admin_users_path %>
  </div>

<% end %>

<script>
  $("#user_group_ids").select2()
</script>

app/views/admin/users/index.html.erb
<h1>Admin Users</h1>
<table class="table">
<thead>
  <tr>
    <th>ID</th>
    <th>Email</th>
    <th>Groups</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody class="sortable">
  <% @users.each do |user| %>
    <tr data-reorder-url="<%= reorder_admin_user_path(user) %>">
      <td><span class="sortable_icon">☰</span><%= user.id %></td>
      <td><%= user.email %></td>
      <td>
        <% user.groups.each do |group| %>
          <%= group.name%><br>
        <% end %>
      </td>
      <td>
        <%#= link_to "上移", reorder_admin_user_path(user, :position => :up), :method => :post, :class => "btn btn-default" %>
        <%#= link_to "下移", reorder_admin_user_path(user, :position => :down), :method => :post, :class => "btn btn-default" %>
        <%= link_to "置頂", reorder_admin_user_path(user, :position => :first), :method => :post, :class => "btn btn-default" %>
        <%= link_to "置底", reorder_admin_user_path(user, :position => :last), :method => :post, :class => "btn btn-default" %>
      </td>
      <td><%= link_to "Edit", edit_admin_user_path(user), class:"btn btn-default"  %></td>
      <td><%= link_to "Edit Profile", edit_admin_user_profile_path(user), class:"btn btn-default" %></td>
    </tr>
  <% end %>
</tbody>
</table>

<script>
  $( ".sortable" ).sortable({
    axis: 'y',      // 限制只能上下拖曳
    cursor: 'tr',   // 拖曳整個 tr
    handle: ".sortable_icon",       // 限制只有點icon ☰ 才能開始脫衣，砍掉這行的話，會是整個tr都可以拖曳
    stop: function(e, ui){          // 當拖曳結束時，會掉用此方法
      ui.item.children('td').effect('hightlight', {}, 1000)
    },
    update: function(e, ui){        // 當拖拉結束並且 DOM 上的位置變更時，會調用這個方法
      reorder_url = ui.item.data('reorder-url')
      position = ui.item.index()    // 取得順序
      $.ajax({
        type: 'POST',
        url: reorder_url,
        dataType: 'json',
        data: {position: position}
      })
    }
  });
</script>